/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define mciconst const
#else
#define mciconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN mci_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((mci_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE mcirestart( mciin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct mci_buffer_state *YY_BUFFER_STATE;

extern int mcileng;
extern FILE *mciin, *mciout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		mciless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the mciless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define mciless(n) \
	do \
		{ \
		/* Undo effects of setting up mcitext. */ \
		*mci_cp = mci_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		mci_c_buf_p = mci_cp = mci_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up mcitext again */ \
		} \
	while ( 0 )

#define unput(c) mciunput( c, mcitext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int mci_size_t;


struct mci_buffer_state
	{
	FILE *mci_input_file;

	char *mci_ch_buf;		/* input buffer */
	char *mci_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	mci_size_t mci_buf_size;

	/* Number of characters read into mci_ch_buf, not including EOB
	 * characters.
	 */
	int mci_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int mci_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int mci_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int mci_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int mci_fill_buffer;

	int mci_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via mcirestart()), so that the user can continue scanning by
	 * just pointing mciin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE mci_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER mci_current_buffer


/* mci_hold_char holds the character lost when mcitext is formed. */
static char mci_hold_char;

static int mci_n_chars;		/* number of characters read into mci_ch_buf */


int mcileng;

/* Points to current character in buffer. */
static char *mci_c_buf_p = (char *) 0;
static int mci_init = 1;		/* whether we need to initialize */
static int mci_start = 0;	/* start state number */

/* Flag which is used to allow mciwrap()'s to do buffer switches
 * instead of setting up a fresh mciin.  A bit of a hack ...
 */
static int mci_did_buffer_switch_on_eof;

void mcirestart YY_PROTO(( FILE *input_file ));

void mci_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void mci_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE mci_create_buffer YY_PROTO(( FILE *file, int size ));
void mci_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void mci_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void mci_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER mci_flush_buffer( mci_current_buffer )

YY_BUFFER_STATE mci_scan_buffer YY_PROTO(( char *base, mci_size_t size ));
YY_BUFFER_STATE mci_scan_string YY_PROTO(( mciconst char *mci_str ));
YY_BUFFER_STATE mci_scan_bytes YY_PROTO(( mciconst char *bytes, int len ));

static void *mci_flex_alloc YY_PROTO(( mci_size_t ));
static void *mci_flex_realloc YY_PROTO(( void *, mci_size_t ));
static void mci_flex_free YY_PROTO(( void * ));

#define mci_new_buffer mci_create_buffer

#define mci_set_interactive(is_interactive) \
	{ \
	if ( ! mci_current_buffer ) \
		mci_current_buffer = mci_create_buffer( mciin, YY_BUF_SIZE ); \
	mci_current_buffer->mci_is_interactive = is_interactive; \
	}

#define mci_set_bol(at_bol) \
	{ \
	if ( ! mci_current_buffer ) \
		mci_current_buffer = mci_create_buffer( mciin, YY_BUF_SIZE ); \
	mci_current_buffer->mci_at_bol = at_bol; \
	}

#define YY_AT_BOL() (mci_current_buffer->mci_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *mciin = (FILE *) 0, *mciout = (FILE *) 0;
typedef int mci_state_type;
extern char *mcitext;
#define mcitext_ptr mcitext

static mci_state_type mci_get_previous_state YY_PROTO(( void ));
static mci_state_type mci_try_NUL_trans YY_PROTO(( mci_state_type current_state ));
static int mci_get_next_buffer YY_PROTO(( void ));
static void mci_fatal_error YY_PROTO(( mciconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up mcitext.
 */
#define YY_DO_BEFORE_ACTION \
	mcitext_ptr = mci_bp; \
	mcileng = (int) (mci_cp - mci_bp); \
	mci_hold_char = *mci_cp; \
	*mci_cp = '\0'; \
	mci_c_buf_p = mci_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
static mciconst short int mci_acclist[140] =
    {   0,
       32,   30,   31,   27,   30,   31,   28,   31,   30,   31,
       30,   31,   23,   30,   31,   30,   31,   23,   30,   31,
    16402,   20,   30,   31,   19,   30,   31,   23,   30,   31,
       21,   30,   31,   21,   30,   31,   21,   30,   31,   21,
       30,   31,   21,   30,   31,   21,   30,   31,   13,   21,
       30,   31,   14,   21,   30,   31,   15,   21,   30,   31,
       29,    1,16402,   19, 8210,   24,   16,   19,   22,   21,
       21,   12,   21,   21,   21,   21,   21,   21,   21,   19,
       17,   26,   21,   21,    4,   21,   11,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   25,

        7,   21,   10,   21,   21,   21,   21,   21,    2,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
        5,   21,   21,   21,   21,    3,   21,   21,   21,    6,
       21,   21,   21,   21,    8,   21,   21,    9,   21
    } ;

static mciconst short int mci_accept[104] =
    {   0,
        1,    1,    1,    2,    4,    7,    9,   11,   13,   16,
       18,   22,   25,   28,   31,   34,   37,   40,   43,   46,
       49,   53,   57,   61,   61,   62,   62,   63,   64,   64,
       65,   66,   67,   68,   68,   68,   68,   68,   69,   70,
       71,   72,   74,   75,   76,   77,   78,   79,   80,   81,
       81,   82,   82,   83,   84,   85,   87,   89,   90,   91,
       92,   93,   93,   94,   95,   96,   97,   98,   99,  100,
      101,  103,  105,  106,  107,  108,  109,  111,  112,  113,
      114,  115,  116,  117,  118,  119,  120,  121,  123,  124,
      125,  126,  128,  129,  130,  132,  133,  134,  135,  137,

      138,  140,  140
    } ;

static mciconst int mci_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        7,    1,    1,    7,    8,    9,    1,   10,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    7,    1,
       13,    1,    1,    1,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   23,   24,   25,   26,   27,   28,
       23,   29,   30,   31,   32,   33,   23,   34,   35,   36,
        6,    1,    6,    1,   23,    1,   23,   23,   23,   23,

       37,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   23,   23,   23,   23,   23,
       23,   23,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static mciconst int mci_meta[38] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    1,    3,
        3,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3
    } ;

static mciconst short int mci_base[106] =
    {   0,
        0,    0,  169,  170,  170,  170,  164,  164,  170,   29,
       39,   43,   50,  153,   14,    0,   46,  136,  132,  141,
        0,    0,    0,  158,  157,  157,  170,  150,   55,   59,
      170,  170,   61,   67,   63,   72,   75,   79,  170,    0,
      129,  141,  136,  136,  136,  126,  137,  120,   83,   85,
       89,   93,   95,  136,  127,    0,  126,  122,  114,  128,
      120,   97,  108,  120,  116,  121,  113,  111,  119,   99,
        0,    0,  108,  113,  117,  108,    0,  105,  107,   95,
      116,  100,  110,  103,  108,   99,   87,    0,  103,   83,
       89,    0,   84,   95,    0,   82,   78,   79,    0,   26,

        0,  170,  119,  122,   42
    } ;

static mciconst short int mci_def[106] =
    {   0,
      102,    1,  102,  102,  102,  102,  103,  104,  102,  102,
      102,  102,  102,  102,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  103,  103,  104,  102,   11,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  102,  102,
      102,  102,  102,  105,  105,  105,  105,  105,  105,  105,
      105,  102,  105,  105,  105,  105,  105,  105,  105,  102,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,

      105,    0,  102,  102,  102
    } ;

static mciconst short int mci_nxt[208] =
    {   0,
        4,    5,    6,    7,    8,    9,    9,   10,   11,   12,
       13,   14,    9,   15,   16,   17,   16,   16,   16,   18,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   19,
       20,   16,   16,   21,   22,   23,   16,   28,   29,   30,
       31,   31,   41,   42,   40,   31,   43,   32,   33,   33,
       35,   28,   36,   36,   37,  101,   34,   35,   28,   38,
       38,   37,   44,   28,   29,   29,   45,   28,   49,   49,
       33,   33,   52,   52,   50,   34,   51,   51,   34,   35,
       28,   36,   36,   37,   53,   53,   35,   28,   38,   38,
       37,   28,   49,   49,   51,   51,  100,   34,   51,   51,

       62,   99,   52,   52,   53,   53,   70,   70,   70,   70,
       84,   98,   97,   96,   95,   94,   93,   92,   85,   24,
       91,   24,   26,   26,   26,   90,   89,   88,   87,   86,
       83,   82,   81,   80,   79,   78,   77,   76,   75,   74,
       73,   72,   71,   69,   68,   67,   66,   65,   64,   63,
       61,   60,   59,   58,   57,   56,   55,   54,  102,   27,
       25,   25,   48,   47,   46,   39,   27,   25,  102,    3,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,  102,  102,  102,  102
    } ;

static mciconst short int mci_chk[208] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,   10,   10,   10,
       11,   11,   15,   15,  105,   11,   15,   11,   11,   11,
       12,   12,   12,   12,   12,  100,   11,   13,   13,   13,
       13,   13,   17,   29,   29,   29,   17,   30,   30,   30,
       33,   33,   35,   35,   34,   11,   34,   34,   33,   36,
       36,   36,   36,   36,   37,   37,   38,   38,   38,   38,
       38,   49,   49,   49,   50,   50,   98,   33,   51,   51,

       52,   97,   52,   52,   53,   53,   62,   62,   70,   70,
       80,   96,   94,   93,   91,   90,   89,   87,   80,  103,
       86,  103,  104,  104,  104,   85,   84,   83,   82,   81,
       79,   78,   76,   75,   74,   73,   69,   68,   67,   66,
       65,   64,   63,   61,   60,   59,   58,   57,   55,   54,
       48,   47,   46,   45,   44,   43,   42,   41,   28,   26,
       25,   24,   20,   19,   18,   14,    8,    7,    3,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,

      102,  102,  102,  102,  102,  102,  102
    } ;

static mci_state_type mci_state_buf[YY_BUF_SIZE + 2], *mci_state_ptr;
static char *mci_full_match;
static int mci_lp;
static int mci_looking_for_trail_begin = 0;
static int mci_full_lp;
static int *mci_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*mci_cp = mci_hold_char; /* undo effects of setting up mcitext */ \
mci_cp = mci_full_match; /* restore poss. backed-over text */ \
mci_lp = mci_full_lp; /* restore orig. accepting pos. */ \
mci_state_ptr = mci_full_state; /* restore orig. state */ \
mci_current_state = *mci_state_ptr; /* restore curr. state */ \
++mci_lp; \
goto find_rule; \
}
#define mcimore() mcimore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *mcitext;
#line 1 "mcinp.l"
#define INITIAL 0
#line 2 "mcinp.l"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "mcglobal.h"
#include "sunpos.h"
#include "mcground.h"
#include "mcparse.h"
#include "mcprint.h"
#include "mc_module.hh"
#include "mcsyntax.h"
#include "mc_group.t"

Date ConvertToDate(char *t);

Time ConvertToTime(char *t);

void AssignItem(char *to, char *from);


/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int mciwrap YY_PROTO(( void ));
#else
extern int mciwrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void mciunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef mcitext_ptr
static void mci_flex_strncpy YY_PROTO(( char *, mciconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int mci_flex_strlen YY_PROTO(( mciconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int mciinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int mci_start_stack_ptr = 0;
static int mci_start_stack_depth = 0;
static int *mci_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void mci_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void mci_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int mci_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( mcitext, mcileng, 1, mciout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( mci_current_buffer->mci_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( mciin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( mciin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, mciin )) == 0) \
		  && ferror( mciin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "mciterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef mciterminate
#define mciterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) mci_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int mcilex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after mcitext and mcileng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register mci_state_type mci_current_state;
	register char *mci_cp, *mci_bp;
	register int mci_act;

#line 25 "mcinp.l"



	if ( mci_init )
		{
		mci_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! mci_start )
			mci_start = 1;	/* first start state */

		if ( ! mciin )
			mciin = stdin;

		if ( ! mciout )
			mciout = stdout;

		if ( ! mci_current_buffer )
			mci_current_buffer =
				mci_create_buffer( mciin, YY_BUF_SIZE );

		mci_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		mci_cp = mci_c_buf_p;

		/* Support of mcitext. */
		*mci_cp = mci_hold_char;

		/* mci_bp points to the position in mci_ch_buf of the start of
		 * the current run.
		 */
		mci_bp = mci_cp;

		mci_current_state = mci_start;
		mci_state_ptr = mci_state_buf;
		*mci_state_ptr++ = mci_current_state;
mci_match:
		do
			{
			register YY_CHAR mci_c = mci_ec[YY_SC_TO_UI(*mci_cp)];
			while ( mci_chk[mci_base[mci_current_state] + mci_c] != mci_current_state )
				{
				mci_current_state = (int) mci_def[mci_current_state];
				if ( mci_current_state >= 103 )
					mci_c = mci_meta[(unsigned int) mci_c];
				}
			mci_current_state = mci_nxt[mci_base[mci_current_state] + (unsigned int) mci_c];
			*mci_state_ptr++ = mci_current_state;
			++mci_cp;
			}
		while ( mci_base[mci_current_state] != 170 );

mci_find_action:
		mci_current_state = *--mci_state_ptr;
		mci_lp = mci_accept[mci_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( mci_lp && mci_lp < mci_accept[mci_current_state + 1] )
				{
				mci_act = mci_acclist[mci_lp];
				if ( mci_act & YY_TRAILING_HEAD_MASK ||
				     mci_looking_for_trail_begin )
					{
					if ( mci_act == mci_looking_for_trail_begin )
						{
						mci_looking_for_trail_begin = 0;
						mci_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( mci_act & YY_TRAILING_MASK )
					{
					mci_looking_for_trail_begin = mci_act & ~YY_TRAILING_MASK;
					mci_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					mci_full_match = mci_cp;
					mci_full_state = mci_state_ptr;
					mci_full_lp = mci_lp;
					break;
					}
				++mci_lp;
				goto find_rule;
				}
			--mci_cp;
			mci_current_state = *--mci_state_ptr;
			mci_lp = mci_accept[mci_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( mci_act )
	{ /* beginning of action switch */
case 1:
*mci_cp = mci_hold_char; /* undo effects of setting up mcitext */
mci_c_buf_p = mci_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up mcitext again */
YY_RULE_SETUP
#line 27 "mcinp.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "mcinp.l"
return (TITLE);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "mcinp.l"
return (CDFIMPORT);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "mcinp.l"
return (AVG);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "mcinp.l"
return (CHEMFILE);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "mcinp.l"
return (SUBDOMAIN);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "mcinp.l"
return (ARRAY);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "mcinp.l"
return (GROUNDLEVEL);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "mcinp.l"
return (GROUNDCLASSES);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 39 "mcinp.l"
return (ASCII);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 41 "mcinp.l"
return (CDF);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 43 "mcinp.l"
return (AS);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 45 "mcinp.l"
{
	      mcilval.ival = X_DIM;
	      return DIMENSION;
	    }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 50 "mcinp.l"
{
	      mcilval.ival = Y_DIM;
	      return DIMENSION;
	    }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "mcinp.l"
{
	      mcilval.ival = Z_DIM;
	      return DIMENSION;
	    }
	YY_BREAK
case 16:
#line 61 "mcinp.l"
case 17:
#line 62 "mcinp.l"
case 18:
YY_RULE_SETUP
#line 62 "mcinp.l"
{
	       mcilval.dval = atof(mcitext);
               return (FLOATNUM);
             }
	YY_BREAK
case 19:
#line 68 "mcinp.l"
case 20:
YY_RULE_SETUP
#line 68 "mcinp.l"
{
	       mcilval.ival = atoi(mcitext);
	       return (INTNUM);
	     }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 73 "mcinp.l"
{
	       AssignItem(mcilval.item, mcitext);
               {
                 Command *tcmd;
                 if (McInterface::mcsect.FindSection(mcitext))
                   return (SECTION);
                 else if (tcmd = McInterface::mccommand.Find(mcitext)) {
                   mcilval.command = tcmd;
                   return (USERCOMMAND);
                 }
                 else
                   return (IDENTIFIER);
               }
             }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 88 "mcinp.l"
return (VARDEFINE);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 90 "mcinp.l"
return (*mcitext);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 "mcinp.l"
return (RANGE);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 94 "mcinp.l"
{
               mcilval.date = ConvertToDate(mcitext);
               return (IDATE);
             }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 99 "mcinp.l"
{
	       mcilval.time = ConvertToTime(mcitext);
	       return (DAYTIME);
	     }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 104 "mcinp.l"
;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 106 "mcinp.l"
inplineno++;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 108 "mcinp.l"
{
              mcitext[strlen(mcitext)-1] = '\0';
	      AssignItem(mcilval.item, mcitext+1);
	      return (STRING);
	    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 114 "mcinp.l"
{
	       fprintf(stderr, "ERROR: Illegal character in Inputfile: %c\n",
	          *mcitext);
	       return (NONSENSE);
	    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "mcinp.l"
ECHO;
	YY_BREAK
			case YY_STATE_EOF(INITIAL):
				mciterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int mci_amount_of_matched_text = (int) (mci_cp - mcitext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*mci_cp = mci_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( mci_current_buffer->mci_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed mciin at a new source and called
			 * mcilex().  If so, then we have to assure
			 * consistency between mci_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			mci_n_chars = mci_current_buffer->mci_n_chars;
			mci_current_buffer->mci_input_file = mciin;
			mci_current_buffer->mci_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for mci_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since mci_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( mci_c_buf_p <= &mci_current_buffer->mci_ch_buf[mci_n_chars] )
			{ /* This was really a NUL. */
			mci_state_type mci_next_state;

			mci_c_buf_p = mcitext_ptr + mci_amount_of_matched_text;

			mci_current_state = mci_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * mci_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			mci_next_state = mci_try_NUL_trans( mci_current_state );

			mci_bp = mcitext_ptr + YY_MORE_ADJ;

			if ( mci_next_state )
				{
				/* Consume the NUL. */
				mci_cp = ++mci_c_buf_p;
				mci_current_state = mci_next_state;
				goto mci_match;
				}

			else
				{
				mci_cp = mci_c_buf_p;
				goto mci_find_action;
				}
			}

		else switch ( mci_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				mci_did_buffer_switch_on_eof = 0;

				if ( mciwrap() )
					{
					/* Note: because we've taken care in
					 * mci_get_next_buffer() to have set up
					 * mcitext, we can now set up
					 * mci_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					mci_c_buf_p = mcitext_ptr + YY_MORE_ADJ;

					mci_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! mci_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				mci_c_buf_p =
					mcitext_ptr + mci_amount_of_matched_text;

				mci_current_state = mci_get_previous_state();

				mci_cp = mci_c_buf_p;
				mci_bp = mcitext_ptr + YY_MORE_ADJ;
				goto mci_match;

			case EOB_ACT_LAST_MATCH:
				mci_c_buf_p =
				&mci_current_buffer->mci_ch_buf[mci_n_chars];

				mci_current_state = mci_get_previous_state();

				mci_cp = mci_c_buf_p;
				mci_bp = mcitext_ptr + YY_MORE_ADJ;
				goto mci_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of mcilex */


/* mci_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int mci_get_next_buffer()
	{
	register char *dest = mci_current_buffer->mci_ch_buf;
	register char *source = mcitext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( mci_c_buf_p > &mci_current_buffer->mci_ch_buf[mci_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( mci_current_buffer->mci_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( mci_c_buf_p - mcitext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (mci_c_buf_p - mcitext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( mci_current_buffer->mci_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		mci_current_buffer->mci_n_chars = mci_n_chars = 0;

	else
		{
		int num_to_read =
			mci_current_buffer->mci_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = mci_current_buffer;

			int mci_c_buf_p_offset =
				(int) (mci_c_buf_p - b->mci_ch_buf);

			if ( b->mci_is_our_buffer )
				{
				int new_size = b->mci_buf_size * 2;

				if ( new_size <= 0 )
					b->mci_buf_size += b->mci_buf_size / 8;
				else
					b->mci_buf_size *= 2;

				b->mci_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					mci_flex_realloc( (void *) b->mci_ch_buf,
							 b->mci_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->mci_ch_buf = 0;

			if ( ! b->mci_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			mci_c_buf_p = &b->mci_ch_buf[mci_c_buf_p_offset];

			num_to_read = mci_current_buffer->mci_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&mci_current_buffer->mci_ch_buf[number_to_move]),
			mci_n_chars, num_to_read );

		mci_current_buffer->mci_n_chars = mci_n_chars;
		}

	if ( mci_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			mcirestart( mciin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			mci_current_buffer->mci_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	mci_n_chars += number_to_move;
	mci_current_buffer->mci_ch_buf[mci_n_chars] = YY_END_OF_BUFFER_CHAR;
	mci_current_buffer->mci_ch_buf[mci_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	mcitext_ptr = &mci_current_buffer->mci_ch_buf[0];

	return ret_val;
	}


/* mci_get_previous_state - get the state just before the EOB char was reached */

static mci_state_type mci_get_previous_state()
	{
	register mci_state_type mci_current_state;
	register char *mci_cp;

	mci_current_state = mci_start;
	mci_state_ptr = mci_state_buf;
	*mci_state_ptr++ = mci_current_state;

	for ( mci_cp = mcitext_ptr + YY_MORE_ADJ; mci_cp < mci_c_buf_p; ++mci_cp )
		{
		register YY_CHAR mci_c = (*mci_cp ? mci_ec[YY_SC_TO_UI(*mci_cp)] : 1);
		while ( mci_chk[mci_base[mci_current_state] + mci_c] != mci_current_state )
			{
			mci_current_state = (int) mci_def[mci_current_state];
			if ( mci_current_state >= 103 )
				mci_c = mci_meta[(unsigned int) mci_c];
			}
		mci_current_state = mci_nxt[mci_base[mci_current_state] + (unsigned int) mci_c];
		*mci_state_ptr++ = mci_current_state;
		}

	return mci_current_state;
	}


/* mci_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = mci_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static mci_state_type mci_try_NUL_trans( mci_state_type mci_current_state )
#else
static mci_state_type mci_try_NUL_trans( mci_current_state )
mci_state_type mci_current_state;
#endif
	{
	register int mci_is_jam;

	register YY_CHAR mci_c = 1;
	while ( mci_chk[mci_base[mci_current_state] + mci_c] != mci_current_state )
		{
		mci_current_state = (int) mci_def[mci_current_state];
		if ( mci_current_state >= 103 )
			mci_c = mci_meta[(unsigned int) mci_c];
		}
	mci_current_state = mci_nxt[mci_base[mci_current_state] + (unsigned int) mci_c];
	mci_is_jam = (mci_current_state == 102);
	if ( ! mci_is_jam )
		*mci_state_ptr++ = mci_current_state;

	return mci_is_jam ? 0 : mci_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void mciunput( int c, register char *mci_bp )
#else
static void mciunput( c, mci_bp )
int c;
register char *mci_bp;
#endif
	{
	register char *mci_cp = mci_c_buf_p;

	/* undo effects of setting up mcitext */
	*mci_cp = mci_hold_char;

	if ( mci_cp < mci_current_buffer->mci_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = mci_n_chars + 2;
		register char *dest = &mci_current_buffer->mci_ch_buf[
					mci_current_buffer->mci_buf_size + 2];
		register char *source =
				&mci_current_buffer->mci_ch_buf[number_to_move];

		while ( source > mci_current_buffer->mci_ch_buf )
			*--dest = *--source;

		mci_cp += (int) (dest - source);
		mci_bp += (int) (dest - source);
		mci_current_buffer->mci_n_chars =
			mci_n_chars = mci_current_buffer->mci_buf_size;

		if ( mci_cp < mci_current_buffer->mci_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--mci_cp = (char) c;


	mcitext_ptr = mci_bp;
	mci_hold_char = *mci_cp;
	mci_c_buf_p = mci_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int mciinput()
#else
static int input()
#endif
	{
	int c;

	*mci_c_buf_p = mci_hold_char;

	if ( *mci_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* mci_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( mci_c_buf_p < &mci_current_buffer->mci_ch_buf[mci_n_chars] )
			/* This was really a NUL. */
			*mci_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = mci_c_buf_p - mcitext_ptr;
			++mci_c_buf_p;

			switch ( mci_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because mci_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					mcirestart( mciin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( mciwrap() )
						return EOF;

					if ( ! mci_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return mciinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					mci_c_buf_p = mcitext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) mci_c_buf_p;	/* cast for 8-bit char's */
	*mci_c_buf_p = '\0';	/* preserve mcitext */
	mci_hold_char = *++mci_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void mcirestart( FILE *input_file )
#else
void mcirestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! mci_current_buffer )
		mci_current_buffer = mci_create_buffer( mciin, YY_BUF_SIZE );

	mci_init_buffer( mci_current_buffer, input_file );
	mci_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void mci_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void mci_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( mci_current_buffer == new_buffer )
		return;

	if ( mci_current_buffer )
		{
		/* Flush out information for old buffer. */
		*mci_c_buf_p = mci_hold_char;
		mci_current_buffer->mci_buf_pos = mci_c_buf_p;
		mci_current_buffer->mci_n_chars = mci_n_chars;
		}

	mci_current_buffer = new_buffer;
	mci_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (mciwrap()) processing, but the only time this flag
	 * is looked at is after mciwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	mci_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void mci_load_buffer_state( void )
#else
void mci_load_buffer_state()
#endif
	{
	mci_n_chars = mci_current_buffer->mci_n_chars;
	mcitext_ptr = mci_c_buf_p = mci_current_buffer->mci_buf_pos;
	mciin = mci_current_buffer->mci_input_file;
	mci_hold_char = *mci_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mci_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE mci_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) mci_flex_alloc( sizeof( struct mci_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mci_create_buffer()" );

	b->mci_buf_size = size;

	/* mci_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->mci_ch_buf = (char *) mci_flex_alloc( b->mci_buf_size + 2 );
	if ( ! b->mci_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in mci_create_buffer()" );

	b->mci_is_our_buffer = 1;

	mci_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void mci_delete_buffer( YY_BUFFER_STATE b )
#else
void mci_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == mci_current_buffer )
		mci_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->mci_is_our_buffer )
		mci_flex_free( (void *) b->mci_ch_buf );

	mci_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void mci_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void mci_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	mci_flush_buffer( b );

	b->mci_input_file = file;
	b->mci_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->mci_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->mci_is_interactive = 0;
#else
	b->mci_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void mci_flush_buffer( YY_BUFFER_STATE b )
#else
void mci_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->mci_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->mci_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->mci_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->mci_buf_pos = &b->mci_ch_buf[0];

	b->mci_at_bol = 1;
	b->mci_buffer_status = YY_BUFFER_NEW;

	if ( b == mci_current_buffer )
		mci_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mci_scan_buffer( char *base, mci_size_t size )
#else
YY_BUFFER_STATE mci_scan_buffer( base, size )
char *base;
mci_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) mci_flex_alloc( sizeof( struct mci_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in mci_scan_buffer()" );

	b->mci_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->mci_buf_pos = b->mci_ch_buf = base;
	b->mci_is_our_buffer = 0;
	b->mci_input_file = 0;
	b->mci_n_chars = b->mci_buf_size;
	b->mci_is_interactive = 0;
	b->mci_at_bol = 1;
	b->mci_fill_buffer = 0;
	b->mci_buffer_status = YY_BUFFER_NEW;

	mci_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mci_scan_string( mciconst char *mci_str )
#else
YY_BUFFER_STATE mci_scan_string( mci_str )
mciconst char *mci_str;
#endif
	{
	int len;
	for ( len = 0; mci_str[len]; ++len )
		;

	return mci_scan_bytes( mci_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE mci_scan_bytes( mciconst char *bytes, int len )
#else
YY_BUFFER_STATE mci_scan_bytes( bytes, len )
mciconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	mci_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) mci_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in mci_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = mci_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in mci_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->mci_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void mci_push_state( int new_state )
#else
static void mci_push_state( new_state )
int new_state;
#endif
	{
	if ( mci_start_stack_ptr >= mci_start_stack_depth )
		{
		mci_size_t new_size;

		mci_start_stack_depth += YY_START_STACK_INCR;
		new_size = mci_start_stack_depth * sizeof( int );

		if ( ! mci_start_stack )
			mci_start_stack = (int *) mci_flex_alloc( new_size );

		else
			mci_start_stack = (int *) mci_flex_realloc(
					(void *) mci_start_stack, new_size );

		if ( ! mci_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	mci_start_stack[mci_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void mci_pop_state()
	{
	if ( --mci_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(mci_start_stack[mci_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int mci_top_state()
	{
	return mci_start_stack[mci_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void mci_fatal_error( mciconst char msg[] )
#else
static void mci_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine mciless() so it works in section 3 code. */

#undef mciless
#define mciless(n) \
	do \
		{ \
		/* Undo effects of setting up mcitext. */ \
		mcitext[mcileng] = mci_hold_char; \
		mci_c_buf_p = mcitext + n; \
		mci_hold_char = *mci_c_buf_p; \
		*mci_c_buf_p = '\0'; \
		mcileng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef mcitext_ptr
#ifdef YY_USE_PROTOS
static void mci_flex_strncpy( char *s1, mciconst char *s2, int n )
#else
static void mci_flex_strncpy( s1, s2, n )
char *s1;
mciconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int mci_flex_strlen( mciconst char *s )
#else
static int mci_flex_strlen( s )
mciconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *mci_flex_alloc( mci_size_t size )
#else
static void *mci_flex_alloc( size )
mci_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *mci_flex_realloc( void *ptr, mci_size_t size )
#else
static void *mci_flex_realloc( ptr, size )
void *ptr;
mci_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void mci_flex_free( void *ptr )
#else
static void mci_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	mcilex();
	return 0;
	}
#endif
#line 120 "mcinp.l"


Date ConvertToDate(char *t)
{
  char *p;
  Date d;
  for (p = t; *p != '-'; p++);
  *p = '\0'; d.month = atoi(t); t = ++p;
  while (*p != '-')  p++;
  *p = '\0'; d.day = atoi(t);
  d.year = atoi(++p);
  if (d.day < 1 || d.day > 31 || d.month < 1 || d.month > 12 || d.year < 1900 ||
      d.year > 2100)  {
    fprintf(stderr, "Impossible date: %i-%i-%i!\n", d.month, d.day, d.year);
    d.year = -1;
  }
  return (d);
}

Time ConvertToTime(char *tname)
{
  char *p;
  Time t;
  for (p = tname; *p != ':'; p++);
  *p = '\0'; t.hour = atoi(tname);
  t.minute = atoi(++p);
  if (t.hour > 23 || t.minute > 59)  {
    fprintf(stderr, "Impossible Time: %i:%i\n", t.hour, t.minute);
    t.hour = -1;
  }
  return (t);
}

void AssignItem(char *to, char *from)
{
  if (strlen(from) >= (size_t)ITEMLEN)
    printf("Warning: Item *s is too long and will be cut to 63 Characters\n");
  strncpy(to, from, ITEMLEN);
}

